"""create_avatar_table

Revision ID: a9493f5d6165
Create Date: 2023-12-03 18:01:10.093443
"""

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9493f5d6165'
down_revision = '65d97cb437d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_avatar',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    mysql_collate='utf8mb4_bin'
    )
    op.create_unique_constraint(None, 'auth_oauth_user_connection', ['id'])
    op.create_unique_constraint(None, 'auth_session', ['id'])
    op.create_unique_constraint(None, 'auth_user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_user', type_='unique')
    op.drop_constraint(None, 'auth_session', type_='unique')
    op.drop_constraint(None, 'auth_oauth_user_connection', type_='unique')
    op.drop_table('auth_avatar')
    # ### end Alembic commands ###
