name: test

on:
  push:
    branches: [develop]
  pull_request:

env:
  PYTHON_VERSION: "3.11"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Cache virtual environment
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/pip
            ~/.cache/pypoetry
          key: ${{ runner.os }}-venv-${{ hashFiles('poetry.lock') }}
      - name: Setup poetry
        run: |
          pip install poetry poethepoet
          poetry install -n --no-root --sync
      - run: poe test
